port: /dev/ttyUSB0
baudrate: 115200
show_prefix: true
navigation_colors:
  background: yellow
head:
  col:
    - frame:
        name: 'Last:'
        borders: true
        window:
          status:
            size:
              rows: 1
              cols: 100
            prefix: ''
            show_prefix: true
            initial: '...'
    - frame:
        name: 'Error:'
        borders: true
        colors:
          foreground: red
        window:
          status:
            size:
              rows: 1
              cols: 100
            prefix: 'ERR: '
            show_prefix: false
            colors:
              foreground: red
            initial: '...'
    - space:
        size:
          rows: 1
          cols: 102
        colors:
          background: white
logs:
  - prefix: 'DBG: '
    show: true
    colors:
      foreground: grey
  - prefix: 'INF: '
    show: true
  - prefix: 'WRN: '
    show: true
    colors:
      foreground: red
  - prefix: 'ERR: '
    show: true
    colors:
      background: red
  - prefix: ''
    show: false