port: /dev/ttyUSB0
baudrate: 115200
logs:
  - prefix: 'DBG: '
    show: true
    colors:
      foreground: grey
  - prefix: 'INF: '
    show: true
  - prefix: 'WRN: '
    show: true
    colors:
      foreground: red
  - prefix: 'ERR: '
    show: true
    colors:
      background: red
  - prefix: ''
    show: false