port: /dev/ttyUSB0
baudrate: 115200
show_prefix: true
navigation_colors:
  background: red
head:
  col:
    - frame:
        name: 'Last:'
        borders: true
        window:
          status:
            size:
              rows: 1
              cols: 100
            prefix: ''
            show_prefix: true
            initial: '<no data>'
    - space:
        cols: 1
    - frame:
        name: 'Error:'
        borders: true
        colors:
          foreground: red
        window:
          status:
            size:
              rows: 1
              cols: 100
            prefix: 'ERR: '
            show_prefix: false
            colors:
              foreground: red
            initial: '<no data>'
logs:
  - prefix: 'DBG: '
    show: true
    colors:
      foreground: 8
  - prefix: 'INF: '
    show: true
    colors:
      foreground: -1
      background: -1
  - prefix: 'WRN: '
    show: true
    colors:
      foreground: red
  - prefix: 'ERR: '
    show: true
    colors:
      background: red
  - prefix: ''
    show: false