port: /dev/ttyUSB0
baudrate: 115200
head:
  col:
    - frame:
        name: 'Status:'
        borders: true
        window:
          status:
            size:
              - 1
              - 100
            prefix: ''
            show_prefix: true
            initial: '<no data>'
    - frame:
        name: 'Error:'
        borders: true
        window:
          status:
            size:
              - 1
              - 100
            prefix: 'ERR: '
            show_prefix: false
            initial: '<no data>'
